ARG python_ver=3.9
ARG os_ver=alpine

FROM python:${python_ver}-${os_ver}

WORKDIR /hw1

COPY requirements.txt /hw1
RUN pip3 install --upgrade pip -r requirements.txt

COPY . /hw1

EXPOSE 5000

ENTRYPOINT ["python3"]
CMD ["main.py"]