name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Python Pylin GitHub Action
      uses: fylein/python-pylint-github-action@v1
      with:
        args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc devops-course
