name: Python linter 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v1
      - 
        uses: ricardochaves/python-lint@v1.4.0
