name: Build after changes

on:
  push:
    branches: [ "master" ]

jobs:
  lint:
    uses: ./.github/workflows/pylint.yml
  build_push:
    needs: lint
    uses: ./.github/workflows/build_push.yml
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy:
    needs: build_push
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker pull akon1te/devops_course:latest
          docker run ailurus1/devops_course:latest
